// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.0

package db

import (
	"time"
)

type Account struct {
	ID        int64     `json:"id"`
	Onwer     string    `json:"onwer"`
	CreatedAt time.Time `json:"created_at"`
	Currency  string    `json:"currency"`
	Balance   int64     `json:"balance"`
}

type Entry struct {
	ID        int64     `json:"id"`
	AccountID int64     `json:"account_id"`
	CreatedAt time.Time `json:"created_at"`
	Amount    int64     `json:"amount"`
}

type Transfer struct {
	ID            int64     `json:"id"`
	FromAccountID int64     `json:"from_account_id"`
	ToAccountID   int64     `json:"to_account_id"`
	CreatedAt     time.Time `json:"created_at"`
	Amount        int64     `json:"amount"`
}
