on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    name: Test
    run-on: ubuntu-latest

    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: secret
          POSTGRES_DB: postgres
        options:
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      steps:
        - name: Set up Go
          uses: actions/setup-go@v3
          with:
            go-version: '1.19'

          id: go

        - name: Checkout code
          uses: actions/checkout@v3

        - name: Install postgresql client
          run: apt-get install --yes postgres-client

        - name: Migration
          run: make migration
        
        - name: Test
          run: make test
  